### ISSUE TITLE
Library status?

### ISSUE THREAD

**Issue by jskeet** [pavpen/NationBuilderAPI#4]
I'm considering using the NationBuilder API, and would love to do it from C#. The library was last updated 2 years ago... I'm *guessing* the underlying API has changed a fair amount since then - any plans for continuing this, or is it effectively on-hold? (I completely understand if so... open source commitments can play havoc with a home life.)

**Comment by pavpen** [comment]
Hi, @jskeet.

Yes, I'm no longer working on this project.  It was from a campaign some time ago.

I'm not sure how much the API would have changed since then.  There are unit tests in the project.  If you run them, they should tell you which library calls work as expected, and which ones would fail.

Running the unit tests requires configuring a nation for testing.  You used to get a sandbox nation when you sign up as a Nation Builder developer.

It should also be noted that this library doesn't cover all of the Nation Builder end points.  It covers mostly people, lists and donations.  Of course, other endpoints can be added.

If anyone wants to continue development, I would welcome a new project owner.  People can also create their forks off of this one.

I really think web services should use standards like WADL and WSDL to export their endpoints, so people don't have to write wrapper libraries in each language they want to use, but sometimes there isn't too much choice.

**Comment by jskeet** [comment]
Thanks for the detail. I'm definitely not in a position to take it on, but I'll bear it in mind if I end up using the API. Thanks for getting back to me. I'll close the issue as it was really asking for more info.
